#! /bin/bash
# Bohdon Sayre bashrc
# github.com/bohdon/workspace
# https://github.com/bohdon/workspace

workspace_dir=$(readlink -f "$(dirname "${BASH_SOURCE[0]}")/../../..")

# source common bashrc
. $workspace_dir/prefs/shell/common/bashrc
