
# add ~/bin and workspace/bin to PATH
export PATH="$PATH:$HOME/bin:${workspace_dir}/bin"

# cd aliases
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# make rm, cp, and mv always verbose
alias rm="rm -v"
alias cp="cp -v"
alias mv="mv -v"

alias ls="ls -AFh --color=auto"
alias ll="ls -AFhl"

# apps and tools
alias g='git'
alias pc='pre-commit'
alias d='docker'
alias d-c='docker-compose'
alias r="p4 reconcile -m"
alias rk="p4 revert -k"
alias notify="notify.sh"
alias bigdirs='du -h ./ | grep -v "^-1" | grep "^[0-9]\\+G"'

# find files, and `ls -l` them
find_ls() {
    [[ $1 ]] && path="$1" || path="."
    find "$path" "${@:2}" -type f -exec "ls" -AFhl --color=auto --show-control-chars {} +
}

ff() {
    find_ls "$@"
}

fx() {
    find_ls "$@" -perm -u=x
}

fw() {
    find_ls "$@" -perm -u=w
}

fr() {
    find_ls "$@" ! \( -perm -u=w \)
}

dejunk() {
    find . \( -name ".DS_Store*" -o -name "Thumbs.db" \) -exec "rm" '{}' ';'
}

# Set Project
# Source an env in workspace/.projects/ and cd to the SETPROJ_ROOT if set.
sp() {
    if [[ -z $1 ]]; then
        echo "Usage: setproj PROJECT"
        ls "${workspace_dir}/.projects" | sed -e 's/\..*$//'
        return
    fi

    env_file=${workspace_dir}/.projects/"${1}".env
    if [[ -f "$env_file" ]]; then
        set -a
        # set project name for prompt, can be overridden by env
        export PROJ="$1"
        # clear proj root for cd in case the env doesn't override it
        export SETPROJ_ROOT=
        source $env_file
        set +a
        echo "Set project '${env_file}'"
    else
        echo "Project not found: '${env_file}'"
    fi

    # include project name in prompt
    PS1='\[\033]0;${PROJ:+($PROJ) }\W\007\]${PROJ:+\033[35m($PROJ)\033[00m }\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

    # cd to default root
    if [[ ! -z ${SETPROJ_ROOT} ]]; then
        cd "${SETPROJ_ROOT}" || return
    fi
}
