#! /bin/bash
# Bohdon Sayre bashrc
# designed for use with Git Bash
# https://github.com/bohdon/workspace

workspace_dir=$(readlink -f "$(dirname "${BASH_SOURCE[0]}")/../../..")

# source common bashrc
. $workspace_dir/prefs/shell/common/bashrc

alias open='start' # universal open command
alias rider="rider.cmd"
alias charm="pycharm.cmd"
